### ISSUE TITLE
Empty package

### ISSUE THREAD

**Issue by ghost** [modxcms/ampify#1]
Thank you for this - great development.

I noticed that after installing under the 'extras' dropdown there is 'package' which when you click on it only has the number '1' on the page?

Also I do have a site that already has multiple contexts can you offer any guidance on how I would setup AMP to account for all the other contexts as well? Is it just a case of changing the site_url/amp value?

Thanks,

**Comment by sepiariver** [comment]
Hi @lkfranklin sorry I didn't see this earlier. I have a fix for the empty menu item in the latest build(s).

As far as using Ampify with multiple pre-existing Contexts, here's some things to consider:
1. You can still use the `context mode` but you do risk Resource alias collisions. If you have Resources in those various Contexts with the same URI, they may not render properly in the AMP Context.
2. You can use the `param mode`. I'm borrowing some codebase written by Sterc, to possibly enhance this Extra in the following ways:
   1. An output filter Snippet that can help convert your HTML to AMP-compliant markup.
   2. A way to cache responses when `param mode` is used.

So, probably `param mode` is your best bet and caching will come soon.
