### ISSUE TITLE
Unable to explicitly remove AMP pages

### ISSUE THREAD

**Issue by daygon2007** [modxcms/ampify#2]
Hello,

I'm not sure if I'm missing something or doing something the wrong way but maybe I can get some clarification on how to allow AMP pages per resource. Here's what I've tried so far:

## SET UP
I have set up using context mode, I followed the tutorial on the home page of the project. I was able to get AMP-ify working perfectly, that's for the details on setting it up.

## PROBLEM
I don't want every page to have an AMP version, just article pieces like blogs. Currently if I save my blog list page and go to www.example.com/amp/blog it shows an amp page which I do not want it to do, I want it to revert back to www.example.com/blog **OR** www.example.com/amp/blog but not use the AMP template.

## What Ive Tried
1. In the plugin properties:
   1. Added value of `false-y` to `amp_tv` (tested failed and reverted)
   1. Added new property `exclude_amp_tv`, created new TV called `exclude_amp_template` and assigned it as the value of `exclude_amp_tv`
      1. `exclude_amp_template` is a single select dropdown with the the values of `Include==true-y||Exclude==false-y`. When all of this didnt work I removed it.
   1. I also created a TV called amp_tv with a single select dropdown with the the values of `Include==true-y||Exclude==false-y`. When set to exclude, it didnt work.

So I'm not sure what else I'm missing here, unless theres something I need to do in the plugin properties to get this to work properly.

**Comment by sepiariver** [comment]
Hi @daygon2007

Just to clarify:

The `amp_tv` plugin property holds the name of the TV. So if your TV is named "exclude_amp_template" then put that string into the `amp_tv` plugin properties.

Save it and ensure the property set is the one firing on all enabled plugin events, as described in the documentation.

Then assign the TV to the Template(s), to which your Resources are assigned. If the default TV value is 0 or empty, then all Resources should default to not having an amp page at this point.

You should then be able to enable specific Resources by changing the Tv value for that Resource to the truthy value.

For convenience you can setup a Form Customization rule set that defaults the TV value to 1 when editing any Resource using the blog article Template.

Let me know if this helps....
