### ISSUE TITLE
Bots crawling unwanted AMP URLs

### ISSUE THREAD

**Issue by daygon2007** [modxcms/ampify#4]
With Ampify enabled, every page on the site has an AMP URL, but we're only putting the `<link rel="amphtml" href="" />` on certain pages so only those pages are able to be found by crawlers. The issue I'm currently facing is tools such as SEMrush and other SEO tools with crawlers are pulling pages that do not have the `amphtml` link element and throwing errors. Is there a way to not have amp URLS for every resource?

**Comment by sepiariver** [comment]
Yes @daygon2007 this Extra supports specifying Resources to exclude using a TV. The Plugin must execute in “Context Mode”. There is a workaround documented in the README if you must use “Param Mode” but it’s not as performant.
